routes/web.php
<?php

use App\Http\Controllers\Customer\CustomerController;
use App\Http\Controllers\Delivery\DeliveryBoyController;
use App\Http\Controllers\FrontEndController;
use App\Http\Controllers\Frontend\Vendor\VendorController;
use FontLib\Table\Type\name;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/phpinfo', function () {
    return phpinfo();
});
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/portal-login', function () {
    return view('auth.login');
});

Route::get('/', function () {
    return view('frontend.customer.login');
});

// Route::get('/home-feed', function () {
//     return view('frontend.homefeed');
// });

Route::prefix('/customers')->middleware('guest')->name('customer.')->namespace('Customer')->group(function () {
    Route::get('/login', [CustomerController::class, 'show_login'])->name('login')->middleware('guest');
    Route::post('/login', [CustomerController::class, 'login'])->name('login.attempt');
    Route::get('/register', [CustomerController::class, 'show_register'])->name('customer.register');
    Route::post('/register', [CustomerController::class, 'register'])->name('register.attempt');
    Route::get('/verify-otp', [CustomerController::class, 'show_otp'])->name('show.otppage');
    Route::get('/getproduct-details/{id?}', [FrontEndController::class, 'getProductDetails'])->name('getproduct.details');
    Route::post('/verification-otp', [CustomerController::class, 'verifyOtp'])->name('otp.verify');
    Route::post('/logout', [CustomerController::class, 'logout'])->name('logout');
});

Route::get('/home-feed', 'FrontEndController@homeFeed')->name('homefeed')->middleware('auth:customer', 'verified');
Route::middleware('guest')->group(function () {
    Route::get('/category-products/{name?}/', 'FrontEndController@categoryDetail')->name('category.detail');
    Route::get('/product-detail/{id?}/', 'FrontEndController@productDetail')->name('product.detail');
    Route::get('/product-cart/{qty}/{productid}', 'FrontEndController@productCart')->name('cart.index');
    Route::get('/product-subscribe/{id}', 'FrontEndController@productSubscribe')->name('subscribe.index');
    Route::post('/product-placed-order', 'FrontEndController@productPlacedOrder')->name('placed.order');
    Route::post('/coupon-radeem', 'FrontEndController@redeemCoupon')->name('coupon.radeem');
    Route::post('customer/order/subscription', 'FrontEndController@subscription');
    Route::get('customer/order/subscription-history', 'FrontEndController@subscriptionHistory')->name('customer.subscription.history');
    Route::Post('customer/order/subscription-detail', 'FrontEndController@subscriptionDetail')->name('customer.subscription.detail');
    Route::get('customer/order/jar-history/{id?}', 'FrontEndController@jarHistory')->name('customer.jar.history');
    Route::get('/customer-qr-show', 'Customer\CustomerController@showQr')->name('customer.qr');
    Route::get('customer/wallet-history', 'FrontEndController@walletHistory')->name('customer.wallet.history');
    Route::post('placed_order-schedule', 'FrontEndController@placedOrderSchedule')->name('');
    Route::get('/product-result', 'FrontEndController@search')->name('product.search');
    Route::get('/customer/feedback', 'CustomerController@feedback')->name('customer.feedback');
    Route::post('/customer/feedback/save', 'CustomerController@saveFeedback')->name('customer.feedback.save');
    Route::get('/customer/complain', 'CustomerController@complain')->name('customer.complain');
    Route::post('/customer/complain/save', 'CustomerController@saveComplain')->name('customer.complain.save');
});

// home feed products list



Route::get('/git-pull', 'Api\CommandController@gitpull');
Route::get('/artisan/{name}', 'Api\CommandController@artisanCommand');


Auth::routes();
Route::middleware('auth:web')->group(function () {
    Route::get('/home', 'DashboardController@index')->name('dashboard');
    Route::get('/profile', 'DashboardController@profile')->name('profile');
    Route::post('/profile-save', 'DashboardController@general')->name('profile.save');
    Route::post('/password-save', 'DashboardController@password')->name('password.save');

    // Coupon
    Route::prefix('/coupon')->group(function () {
        Route::get('/', 'CouponController@index')->name('coupon');
        Route::post('/store', 'CouponController@store');
        Route::post('/show', 'CouponController@show');
        Route::get('/{id}/edit', 'CouponController@edit');
        Route::post('/update', 'CouponController@update');
        Route::get('/delete/{id}', 'CouponController@delete');
    });

    // Vendor
    Route::prefix('/vendors')->name('vendor.')->group(function () {
        Route::get('/', 'VendorController@list')->name('list');
        Route::get('/add', 'VendorController@add')->name('add');
        Route::get('/edit/{id?}', 'VendorController@edit')->name('edit');
        Route::post('/save/{id?}', 'VendorController@save')->name('save');
        Route::get('/delete/{id}', 'VendorController@delete')->name('delete');
        Route::get('/approve/{id}', 'VendorController@isApprove')->name('is-approve');
        Route::get('/active/{id}', 'VendorController@isActive')->name('is-active');
        Route::get('/document/view/{id}', 'VendorController@documentView')->name('document.view');
        Route::get('/details/{id}', 'VendorController@detail')->name('detail');
    });
    //complains
    Route::prefix('/complains')->name('complain.')->group(function () {
        Route::get('/', 'ComplainController@list')->name('list');
        Route::get('/add', 'ComplainController@add')->name('add');
        Route::post('/save', 'ComplainController@save')->name('save');
        Route::get('/reply/{id}', 'ComplainController@reply')->name('reply');
        Route::post('/response/{id}', 'ComplainController@response')->name('response');
        Route::get('/delete/{id}', 'ComplainController@delete')->name('delete');
        Route::get('/approve/{id}', 'ComplainController@isApprove')->name('is-approve');
    });

    // QR Code
    Route::prefix('/QR')->group(function () {
        Route::get('/list/{id?}', 'QrCodeController@index');
        Route::get('/Reset/{id}', 'QrCodeController@Reset');
        Route::get('/create', 'QrCodeController@create')->name('QR.CREATE');
    });
    Route::prefix('/customer')->group(function () {
        Route::get('/', 'CustomerController@index')->name('customer.list');
        Route::get('/create', 'CustomerController@create')->name('customer.create');
        Route::post('/store', 'CustomerController@store')->name('customer.store');
        Route::get('/edit/{id}', 'CustomerController@edit')->name('customer.edit');
        Route::get('/view/{id}', 'CustomerController@view')->name('customer.view');
        Route::post('/update', 'CustomerController@update')->name('customer.update');
        Route::get('/delete/{id}', 'CustomerController@delete')->name('customer.delete');
        Route::post('/post-assign-group', 'CustomerController@postAssignGroup')->name('post-assign-group');
    });

    Route::prefix('new/customers')->name('newcustomer.')->group(function () {
        Route::get('/{id?}', 'AssignVendorController@list')->name('list');
        Route::get('/view/{id}', 'AssignVendorController@view')->name('view');
        Route::post('/assign-vendor{id}', 'AssignVendorController@assignVendor')->name('assign');
    });
    //invoice
    Route::prefix('/invoice')->name('invoice.')->group(function () {
        Route::get('/list', 'InvoiceController@index')->name('list');
        Route::get('/view', 'InvoiceController@view')->name('view');
    });
    //group
    Route::prefix('/group')->name('group.')->group(function () {
        Route::get('/list', 'GroupController@index')->name('list');
        Route::get('/create', 'GroupController@create')->name('create');
        Route::post('/store', 'GroupController@store')->name('store');
        Route::get('/member/{id}', 'GroupController@groupCustomer')->name('customer');
        Route::post('/change-member-position', 'GroupController@ChangeMemberPosition')->name('change.member.position');
    });
    //category
    Route::prefix('/category')->name('category.')->group(function () {
        Route::get('/list', 'CategoryController@index')->name('list');
        Route::get('/create', 'CategoryController@create')->name('create');
        Route::post('/store', 'CategoryController@store')->name('store');
    });
    //product
    Route::prefix('/product')->name('product.')->group(function () {
        Route::get('/list', 'ProductController@index')->name('list');
        Route::get('/create', 'ProductController@create')->name('create');
        Route::Post('/store', 'ProductController@store')->name('store');
    });
    //product
    Route::prefix('/deliveryboy')->name('deliveryboy.')->group(function () {
        Route::get('/list', 'DeliveryBoyController@index')->name('list');
        Route::get('/create', 'DeliveryBoyController@create')->name('create');
        Route::Post('/store', 'DeliveryBoyController@store')->name('store');
        Route::get('/assign-group/{id}', 'DeliveryBoyController@assignGroup')->name('assign-group');
        Route::post('/post-assign-group', 'DeliveryBoyController@postAssignGroup')->name('post-assign-group');
        Route::get('/delete/{id}', 'DeliveryBoyController@delete')->name('delete');
        Route::get('/edit/{id}', 'DeliveryBoyController@edit')->name('edit');
        Route::post('/update', 'DeliveryBoyController@update')->name('update');
    });
    //feedback

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
      const CREATED_AT = 'created_at';
     const UPDATED_AT = 'updated_at';
    protected $casts = [
        'created_at' => 'datetime:Y-m-d H:i:s','updated_at' => 'datetime:Y-m-d H:i:s','deleteTime' => 'datetime:Y-m-d H:i:s','addTime' => 'datetime:Y-m-d H:i:s'
    ];
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'products';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'product_title',
        'description',
		'price',
		'is_active',
		'image',
		'unit',
		'category_id',
		'product_type',
    ];
public function category()
    {
        return $this->belongsTo(Category::class,'category_id','id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $user = \Auth::user();
         $products = Product::all();
		$result = [
			'products' => $products,
			];

		return view('product.index')->with(['result'=> $result]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
 		$categories = Category::all();
		$result = [
			'categories' => $categories,
			];
         return view('product.create')->with(['result'=> $result]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $user =  \Auth::user();
        $response = defaultErrorResponse();
        $validator = validateData($request, 'ADD_PRODUCT');
        if ($validator['status'])
               return \Redirect::back()->with('error', $validator['errors']->first());
        \DB::beginTransaction();
        try
        {
			if ($request->hasFile('image'))
				{
					$propertyThumbnailDirectory = 'public/product';
					if (!\Storage::exists($propertyThumbnailDirectory))
					{
						\Storage::makeDirectory($propertyThumbnailDirectory);
					}
					$thumbnailUrl = \Storage::putFile($propertyThumbnailDirectory, $request->file('image'));
					$image = $thumbnailUrl;
			    	$image = str_replace(array("public/"), "", $image);
				}
            Product::create([
                                "product_title"       => $request->product_title,
                                "description"         => $request->description,
                                "price"         	  => $request->price,
                                "unit"         		  => $request->unit,
                                "category_id"         => $request->category_id,
								"image"        		  => $image,
								"is_active"			  => 1,
								"product_type"		  => $request->product_type,
							]);
            \DB::commit();
            return \Redirect()->route('product.list')->with('success', 'Product Added');
        }
        catch (\Exception $e)
        {
            \DB::rollBack();
            return \Redirect::back()->with('error', $e->getMessage());
        }
        return $response;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/frontend/product/detail.blade.php
@extends('frontend.layouts.app')
@section('header')
  <!-- Header -->
    <header
        class="w-100 position-sticky top-0 start-0 end-0 d-flex align-items-center justify-content-between text-white">
        <div class="d-flex align-items-center">
            <a href="{{route('homefeed')}}" class="btn btn-sm text-white ps-0">
                <span class="material-icons d-block">arrow_back</span>
            </a>
            <strong>TNH Water</strong>
        </div>
        <div>
            <a href="#" class="btn btn-sm text-white">
                <span class="material-icons d-block">search</span>
            </a>
        </div>
    </header>
@endsection
@section('content')
{{-- Product Model --}}

<div id="productimagedetail">

</div>

{{-- End Product Model --}}
<div id="allproducts">
    <div class="row g-3 mb-2">
        @foreach($product as $object=>$data)
        <div class="col-6">
            <div class="card border-0 mb-0">
                <div class="card-body">
                    <img src="{{asset('/storage/'.$data->image)}}" alt="" class="card_list_top_img" data onclick="sendRequestForDetails({{ $data->id }})" data-toggle="modal" data-target="#exampleModal" style="cursor: pointer">
                    <h4 class="sub_heading mt-2 mb-0">{{ $data->product_title }}</h4>
                    {{-- <p class = "mt-2 mb-0">{{$data->description}}</p> --}}
                    <div><strong>Can capicity</strong></div>
                    <div><strong>{{ $data->price }}</strong></div>
                    <p class="small text-muted"></p>
                    <a href="{{route('subscribe.index',$data->id)}}" class="btn-theme-sm w-100 mb-1 text-center">Regular Customer Plan</a>
                    <a href="#" class="btn-theme-sm w-100 mb-1 text-center"  onclick = "occasional()"  id = "Occasional">Occasional/Event Plan</a>
                   <div class="row" id = "cartCheckout" style = "display:none">
                       <div class="col-md-8">
                             <input type="hidden" name = "product_id"id="productid" value="{{$data->id}}">
                            <input type="hidden" value="1" name = "hqty" id="hqty">
                            <a href = "#" onclick = "addtocart({{$data->id}})" class="btn-theme-sm w-100 mb-1 text-center">Add To Cart
                            </a>
                       </div>
                       <div class="col-md-4" >
                      <div class="d-inline-flex shadow-sm rounded-pill p-1">
                                <button type="button" class="qty_btn" id="removebtn" onclick="cartqty(1)">
                                    <span class="material-icons d-block">remove</span>
                                </button>
                                <strong class="px-3" id="qty">
                                1
                                </strong>
                                <button type="button" class="qty_btn" id="addbtn" onclick="cartqty(2)">
                                    <span class="material-icons d-block">add</span>
                                </button>
                            </div>
                       </div>
                   </div>
                </div>
            </div>
        </div>

        @endforeach
    </div>
</div>

@endsection
@section('footer')
 <!-- Main Close -->

    <!-- Footer -->
    <footer class="customer_footer fixed-bottom">
        <div class="row text-center align-items-center">
            <div class="col-4">
                <a href="home.html" class="btn d-flex flex-column active">
                    <span class="material-icons"> account_balance_wallet </span>
                    <span>Home</span>
                </a>
            </div>
            <div class="col-4">
                <a href="#" class="btn d-flex flex-column">
                    <span class="material-icons"> home </span>
                    <span>Wallet</span>
                </a>
            </div>
            <div class="col-4">
                <a href="#" class="btn d-flex flex-column">
                    <span class="material-icons"> schedule </span>
                    <span>Schedule</span>
                </a>
            </div>
        </div>
    </footer>
    <!-- Footer Close -->

@endsection
@section('script')
<script>
function occasional()
{
	$('#Occasional').hide();
	$('#cartCheckout').show();
}
    function cartqty($id)
{
	$qty = $('#hqty').val();

	if($id == 1)
	{
		if($qty == 1)
		{
			  toastr.error("Quantity must be greater then 1");
			return ;
		}
		$qty --
		$('#hqty').val($qty);
		$('#qty').html($qty);

	}
	else if ($id == 2)
	{
		$qty ++
		$('#hqty').val($qty);
		$('#qty').html($qty);
	}
}
function addtocart(productid)
{
	let quantity = $("#hqty").val();
	 window.location.assign("{{ url('product-cart') }}" + '/' + quantity +'/' + productid );
}
</script>
<script>
    function sendRequestForDetails(id)
    {
        $.ajax({
           type:'GET',
           url:"{{ route('customer.getproduct.details') }}" + '/' + id,
           async: false,
           data:{id : id},
           success:function(data){
            $("#productimagedetail").html(data);
            $('#exampleModal').modal('show');
           }
        });
    }

    function hideModel()
    {
        $('body').removeClass().removeAttr('style');$('.modal-backdrop').remove();
        $('#exampleModal').modal('hide');
    }
    </script>
@endsection

resources/views/frontend/product/search.blade.php
@extends('frontend.layouts.app')
@section('header')
@include('frontend.layouts.partials.header')
@include('frontend.layouts.partials.sidebar')
@include('frontend.layouts.partials.searchbar')
@endsection
@section('css')
<style>
    #hoverit:hover{
        transform: scale(1.1);
        transition: 500ms ease-in-out;
    }
</style>
@endsection
@section('content')

            <div class="card border-0">
                <div class="card-body">
                    <h4 class="card_heading">Product Related to : '<span style="font-style: italic;color:blue">{{ $queryy }}</span>'</h4>
                    <p class="text">Don't get the ideal result? Back to <a href="{{ route('homefeed') }}" style="text-decoration: none;">Home</a></p>
                    <div class="row g-3">
                        @foreach($products as $object=>$data)
                        <div class="col-4" id="hoverit">
                            <a href="{{route('product.detail',$data->id)}}">
                                <div class="card_list shadow-sm"
                                    style="background:url('{{asset('/storage/'.$data->image)}}') center center;background-size:cover;">
                                    @if($data->is_active==1)
                                    <span>{{ $data->product_title }}</span>
                                    @else
                                    <span> Comming Soon </span>
                                    @endif
                                </div>
                            </a>
                        </div>
                        @endforeach
                    </div>
                </div>
            </div>

@endsection
@section('footer')
@include('frontend.layouts.partials.footer')
@endsection