routes/web.php
<?php

use App\Http\Controllers\Customer\CustomerController;
use App\Http\Controllers\Delivery\DeliveryBoyController;
use App\Http\Controllers\FrontEndController;
use App\Http\Controllers\Frontend\Vendor\VendorController;
use FontLib\Table\Type\name;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/phpinfo', function () {
    return phpinfo();
});
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/portal-login', function () {
    return view('auth.login');
});

Route::get('/', function () {
    return view('frontend.customer.login');
});

// Route::get('/home-feed', function () {
//     return view('frontend.homefeed');
// });

Route::prefix('/customers')->middleware('guest')->name('customer.')->namespace('Customer')->group(function () {
    Route::get('/login', [CustomerController::class, 'show_login'])->name('login')->middleware('guest');
    Route::post('/login', [CustomerController::class, 'login'])->name('login.attempt');
    Route::get('/register', [CustomerController::class, 'show_register'])->name('customer.register');
    Route::post('/register', [CustomerController::class, 'register'])->name('register.attempt');
    Route::get('/verify-otp', [CustomerController::class, 'show_otp'])->name('show.otppage');
    Route::get('/getproduct-details/{id?}', [FrontEndController::class, 'getProductDetails'])->name('getproduct.details');
    Route::post('/verification-otp', [CustomerController::class, 'verifyOtp'])->name('otp.verify');
    Route::post('/logout', [CustomerController::class, 'logout'])->name('logout');
});

Route::get('/home-feed', 'FrontEndController@homeFeed')->name('homefeed')->middleware('auth:customer', 'verified');
Route::middleware('guest')->group(function () {
    Route::get('/category-products/{name?}/', 'FrontEndController@categoryDetail')->name('category.detail');
    Route::get('/product-detail/{id?}/', 'FrontEndController@productDetail')->name('product.detail');
    Route::get('/product-cart/{qty}/{productid}', 'FrontEndController@productCart')->name('cart.index');
    Route::get('/product-subscribe/{id}', 'FrontEndController@productSubscribe')->name('subscribe.index');
    Route::post('/product-placed-order', 'FrontEndController@productPlacedOrder')->name('placed.order');
    Route::post('/coupon-radeem', 'FrontEndController@redeemCoupon')->name('coupon.radeem');
    Route::post('customer/order/subscription', 'FrontEndController@subscription');
    Route::get('customer/order/subscription-history', 'FrontEndController@subscriptionHistory')->name('customer.subscription.history');
    Route::Post('customer/order/subscription-detail', 'FrontEndController@subscriptionDetail')->name('customer.subscription.detail');
    Route::get('customer/order/jar-history/{id?}', 'FrontEndController@jarHistory')->name('customer.jar.history');
    Route::get('/customer-qr-show', 'Customer\CustomerController@showQr')->name('customer.qr');
    Route::get('customer/wallet-history', 'FrontEndController@walletHistory')->name('customer.wallet.history');
    Route::post('placed_order-schedule', 'FrontEndController@placedOrderSchedule')->name('');
    Route::get('/product-result', 'FrontEndController@search')->name('product.search');
    Route::get('/customer/feedback', 'CustomerController@feedback')->name('customer.feedback');
    Route::post('/customer/feedback/save', 'CustomerController@saveFeedback')->name('customer.feedback.save');
    Route::get('/customer/complain', 'CustomerController@complain')->name('customer.complain');
    Route::post('/customer/complain/save', 'CustomerController@saveComplain')->name('customer.complain.save');
});

// home feed products list



Route::get('/git-pull', 'Api\CommandController@gitpull');
Route::get('/artisan/{name}', 'Api\CommandController@artisanCommand');


Auth::routes();
Route::middleware('auth:web')->group(function () {
    Route::get('/home', 'DashboardController@index')->name('dashboard');
    Route::get('/profile', 'DashboardController@profile')->name('profile');
    Route::post('/profile-save', 'DashboardController@general')->name('profile.save');
    Route::post('/password-save', 'DashboardController@password')->name('password.save');

    // Coupon
    Route::prefix('/coupon')->group(function () {
        Route::get('/', 'CouponController@index')->name('coupon');
        Route::post('/store', 'CouponController@store');
        Route::post('/show', 'CouponController@show');
        Route::get('/{id}/edit', 'CouponController@edit');
        Route::post('/update', 'CouponController@update');
        Route::get('/delete/{id}', 'CouponController@delete');
    });

    // Vendor
    Route::prefix('/vendors')->name('vendor.')->group(function () {
        Route::get('/', 'VendorController@list')->name('list');
        Route::get('/add', 'VendorController@add')->name('add');
        Route::get('/edit/{id?}', 'VendorController@edit')->name('edit');
        Route::post('/save/{id?}', 'VendorController@save')->name('save');
        Route::get('/delete/{id}', 'VendorController@delete')->name('delete');
        Route::get('/approve/{id}', 'VendorController@isApprove')->name('is-approve');
        Route::get('/active/{id}', 'VendorController@isActive')->name('is-active');
        Route::get('/document/view/{id}', 'VendorController@documentView')->name('document.view');
        Route::get('/details/{id}', 'VendorController@detail')->name('detail');
    });
    //complains
    Route::prefix('/complains')->name('complain.')->group(function () {
        Route::get('/', 'ComplainController@list')->name('list');
        Route::get('/add', 'ComplainController@add')->name('add');
        Route::post('/save', 'ComplainController@save')->name('save');
        Route::get('/reply/{id}', 'ComplainController@reply')->name('reply');
        Route::post('/response/{id}', 'ComplainController@response')->name('response');
        Route::get('/delete/{id}', 'ComplainController@delete')->name('delete');
        Route::get('/approve/{id}', 'ComplainController@isApprove')->name('is-approve');
    });

    // QR Code
    Route::prefix('/QR')->group(function () {
        Route::get('/list/{id?}', 'QrCodeController@index');
        Route::get('/Reset/{id}', 'QrCodeController@Reset');
        Route::get('/create', 'QrCodeController@create')->name('QR.CREATE');
    });
    Route::prefix('/customer')->group(function () {
        Route::get('/', 'CustomerController@index')->name('customer.list');
        Route::get('/create', 'CustomerController@create')->name('customer.create');
        Route::post('/store', 'CustomerController@store')->name('customer.store');
        Route::get('/edit/{id}', 'CustomerController@edit')->name('customer.edit');
        Route::get('/view/{id}', 'CustomerController@view')->name('customer.view');
        Route::post('/update', 'CustomerController@update')->name('customer.update');
        Route::get('/delete/{id}', 'CustomerController@delete')->name('customer.delete');
        Route::post('/post-assign-group', 'CustomerController@postAssignGroup')->name('post-assign-group');
    });

    Route::prefix('new/customers')->name('newcustomer.')->group(function () {
        Route::get('/{id?}', 'AssignVendorController@list')->name('list');
        Route::get('/view/{id}', 'AssignVendorController@view')->name('view');
        Route::post('/assign-vendor{id}', 'AssignVendorController@assignVendor')->name('assign');
    });
    //invoice
    Route::prefix('/invoice')->name('invoice.')->group(function () {
        Route::get('/list', 'InvoiceController@index')->name('list');
        Route::get('/view', 'InvoiceController@view')->name('view');
    });
    //group
    Route::prefix('/group')->name('group.')->group(function () {
        Route::get('/list', 'GroupController@index')->name('list');
        Route::get('/create', 'GroupController@create')->name('create');
        Route::post('/store', 'GroupController@store')->name('store');
        Route::get('/member/{id}', 'GroupController@groupCustomer')->name('customer');
        Route::post('/change-member-position', 'GroupController@ChangeMemberPosition')->name('change.member.position');
    });
    //category
    Route::prefix('/category')->name('category.')->group(function () {
        Route::get('/list', 'CategoryController@index')->name('list');
        Route::get('/create', 'CategoryController@create')->name('create');
        Route::post('/store', 'CategoryController@store')->name('store');
    });
    //product
    Route::prefix('/product')->name('product.')->group(function () {
        Route::get('/list', 'ProductController@index')->name('list');
        Route::get('/create', 'ProductController@create')->name('create');
        Route::Post('/store', 'ProductController@store')->name('store');
    });
    //product
    Route::prefix('/deliveryboy')->name('deliveryboy.')->group(function () {
        Route::get('/list', 'DeliveryBoyController@index')->name('list');
        Route::get('/create', 'DeliveryBoyController@create')->name('create');
        Route::Post('/store', 'DeliveryBoyController@store')->name('store');
        Route::get('/assign-group/{id}', 'DeliveryBoyController@assignGroup')->name('assign-group');
        Route::post('/post-assign-group', 'DeliveryBoyController@postAssignGroup')->name('post-assign-group');
        Route::get('/delete/{id}', 'DeliveryBoyController@delete')->name('delete');
        Route::get('/edit/{id}', 'DeliveryBoyController@edit')->name('edit');
        Route::post('/update', 'DeliveryBoyController@update')->name('update');
    });
    //feedback

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
     const CREATED_AT = 'created_at';
     const UPDATED_AT = 'updated_at';
    protected $casts = [
        'created_at' => 'datetime:Y-m-d H:i:s','updated_at' => 'datetime:Y-m-d H:i:s','deleteTime' => 'datetime:Y-m-d H:i:s','addTime' => 'datetime:Y-m-d H:i:s'
    ];
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'groups';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'user_id',
    ];

 	public function customer()
    {
        return $this->hasMany(User::class,'group_id','id');
    }
	public function customerUser()
    {
        return $this->hasMany(Customer::class,'group_id','id');
    }
}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use App\Constants\Message;
use App\Constants\ResponseCode;
use App\Customer;
use App\Group;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class GroupController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		$user = \Auth::user();
         $groups = Group::where('user_id',$user->id)->get();
		$result = [
			'groups' => $groups,
			];

		return view('group.index')->with(['result'=> $result]);
    }
 	/**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('group.create');
    }
 	/**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $user =  \Auth::user();
        $response = defaultErrorResponse();
        $validator = validateData($request, 'ADD_GROUP');
        if ($validator['status'])
               return \Redirect::back()->with('error', $validator['errors']->first());
        \DB::beginTransaction();
        try
        {
            $customer =   Group::create([
                                "name"            => $request->name,
								"user_id"        => $user->id,
							]);
            \DB::commit();
            return \Redirect()->route('group.list')->with('success', 'Group Added');
        }
        catch (\Exception $e)
        {
            \DB::rollBack();
            return \Redirect::back()->with('error', $e->getMessage());
        }
        return $response;
    }


    public function listGroup(Request $request)
    {


        $user = \Auth::user();     
        $response = defaultErrorResponse();
        try 
        {

            $groups = Group::where('user_id',$request->user_id)->orderBy('id','DESC')->get();
             $response = makeResponse(ResponseCode::SUCCESS,Message::REQUEST_SUCCESSFUL,true,null,$groups); 
        }
        catch (\Exception $e)
        {
            $response = makeResponse(ResponseCode::FAIL,$e->getMessage(),false);
        }

        return $response;    
    }
    public function groupCustomer($id)
    {
         $customer = Customer::where('group_id',$id)->orderby('serial_number','asc')->get();
         $result = [
			'customer' => $customer,
			
			];
		return view('group.customerlist')->with(['result'=> $result]);
    }
	public function ChangeMemberPosition(Request $request)
	{
	    $response = defaultErrorResponse();
        \DB::beginTransaction();
        try
        {
			$customer = Customer::where('group_id',$request->group_id)->orderby('serial_number','desc')->first();
			if($request->serial_number > 0  &&  $request->serial_number <= $customer->serial_number)
			{
				$customers = Customer::where('id','!=',$request->customer_id)->where('group_id',$request->group_id)->where('serial_number','>=',$request->serial_number)->orderby('serial_number','asc')->get();
				foreach($customers as $customer)
				{
					Customer::where('id',$customer->id)->update([
                               "serial_number" => $customer->serial_number + 1,
							]);
				}
				Customer::where('id',$request->customer_id)->update([
                               "serial_number" => $request->serial_number,
							]);
			}
			else
			{
				return makeResponse(ResponseCode::FAIL,"Invalid Number",false,null); 
			}
 			\DB::commit();
             return makeResponse(ResponseCode::SUCCESS,Message::REQUEST_SUCCESSFUL,true,null); 
        }
        catch (\Exception $e)
        {
            \DB::rollBack();
             return makeResponse(ResponseCode::FAIL,$e->getMessage(),false,null); 

        }
        return $response;
	}
}

resources/views/group/create.blade.php
@extends('portal.layouts.app')

@section('content')
  <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0">Group</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">Add Customer </li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <section class="content">
        <div class="container-fluid">
          <div class="row">
            <!-- left column -->

            <!-- general form elements -->
            <div class="card card-primary" style="width:100%">
              <div class="card-header">
                <h3 class="card-title">Add Group</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action = "{{route('group.store')}}" method = "POST">
				@csrf
                <div class="card-body">

                  <div class="form-group">
                    <label for="exampleInputName">Name</label>
                    <input type="text" name = "name" class="form-control" id="exampleInputName" placeholder="Enter Name">
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>

          </div>

      </section>


@endsection
@section('script')
    
@endsection

resources/views/group/customerlist.blade.php
@extends('portal.layouts.app')

@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Group Member List</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ url('home') }}">Home</a></li>
                        <li class="breadcrumb-item active">Customer List</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- Main content -->

    <div class="row">
    
          
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <table id="table-data" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Position</th>
                                <th>Mobile #</th>
                                <th>customer Name</th>
                                <th>Customer email</th>
                                <th>Customer Address</th>
                                <th>Customer Land Mark</th>
                                <th>Customer QR</th>

                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
									

                            @foreach ($result['customer'] as $index => $data)
                                <tr>
									<td>{{$data->serial_number}}</td>
                                    <td>{{ $data->phone }}</td>
                                    <td>{{ $data->name }}</td>
                                    <td>{{ $data->email }}</td>
                                    <td>{{ $data->address }}</td>
                                    <td>{{ $data->land_mark }}</td>
                                    <td>
                                        <img
                                            src="https://api.qrserver.com/v1/create-qr-code/?data='{{ $data->qr }}'&amp;size=100x100">
                                    </td>
                                    <td>
                        				<a href="#"  class="btn btn-sm btn-info" onclick = "changePosition({{$data->id}},{{$data->group_id}})">Change Position</a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>




{{-- Modal ADD Account  --}}
  
<div class="modal fade" id="ajaxModel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modelHeading"></h4>
            </div>
            <div class="modal-body">
                <form id="account_addition_form" name="account_addition_form">
                @csrf
                <input type = "hidden" name = "customer_id"  id = "customer_id" value = "" />
                <input type = "hidden" name = "group_id"  id = "group_id" value = "" />

                <div>
                  
                    <label>Group</label>
                    <div class="input-group mb-3">
                      <input type = "integer" id = "serial_number" name = "serial_number" class="form-control">
                      </select>
                    </div>
                   <div class="col-sm-offset-2 col-sm-10 mt-2">
                     <button type="submit" class="btn btn-primary" id="saveBtn" value="create">Save changes
                     </button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
</div>


@endsection
@section('script')
<script>
function changePosition(customer_id,group_id)
{
           
       
        $('#customer_id').val(customer_id);
        $('#group_id').val(group_id);

  		$('#saveBtn').val("Change Position");
        $('#account_addition_form').trigger("reset");
        $('#modelHeading').html("Change Position");
        $('#ajaxModel').modal('show');
}




// save changes 


$('#saveBtn').click(function (e) {
        e.preventDefault();
        $(this).html('Sending..');
		$(this).attr("disabled", true);
        $.ajax({
          data: $('#account_addition_form').serialize(),
          url: "{{ url('group/change-member-position') }}",
          type: "POST",
          dataType: 'json',
          success: function (response)
          {
              if(response.data.code == 200)
              {
                $('#account_addition_form').trigger("reset");
                $('#ajaxModel').modal('hide');
                location.reload();
                  toastr.success(response.data.message);
              }
              else if (response.data.code == 400)
              {
                $('#saveBtn').html('Save Changes');
				$('#saveBtn').attr("disabled", false);
                toastr.error(response.data.message);
              }
          },
          error: function (response)
          {
              console.log('Error:', response);
			  $('#saveBtn').attr("disabled", false);
			  toastr.error(response.responseJSON.message);
              $('#saveBtn').html('Save Changes');
          }
      });
    });


</script>
@endsection

resources/views/group/index.blade.php
@extends('portal.layouts.app')

@section('content')
<section class="content-header">
</section>
<!-- Main content -->
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="card card-primary card-outline">
          <div class="card-header">
<a href="{{route('group.create')}}" style="background-color:blue; color:azure; padding:10px; "><i class="fa fa-plus" aria-hidden="true"></i> Add Group</a>
            <div>
              {{-- <h4 class="float-left">Customer Details</h4> --}}
              {{-- <div class="float-right"style="display: inline-flex;">
                   <a title="Add customer" id = "addCustomer" ><i class="fa fa-plus mr-1 red" style="cursor:pointer;"></i></a>
                <!-- <button type="button" class="btn btn-secondary" id = "addBanner">Add Banner</button> -->
              </div> --}}
            </div>
          </div>
          <div class="card-body">
            <table id="table-data" class="table table-bordered table-striped">
              <thead>
                <tr>
                <th>id</th>
                <th>Group Name</th>
                <th> Action </th>
                </tr>
              </thead>
              <tbody>
                @foreach($result['groups'] as $index => $data)
                <tr>
                  <td>{{$data->id}}</td>
 				  <td>{{$data->name}}</td>
                  <td>    <a href="{{ route('group.customer',$data->id) }}" class="btn btn-primary px-4 mt-0 mb-3"><i
                        class="mdi mdi-plus-circle-outline mr-2"></i>View Customers</a></td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <!-- /.col-md-12 -->
    </div>
    <!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content -->
@endsection
@section('script')
    
@endsection