routes/web.php
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/phpinfo', function () {
    return phpinfo();
});
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/portal-login', function () {
    return view('auth.login');
});

Route::get('/', function () {
    return view('frontend.customer.login');
});

// Route::get('/home-feed', function () {
//     return view('frontend.homefeed');
// });

Route::prefix('/customers')->middleware('guest')->name('customer.')->namespace('Customer')->group(function () {
    Route::get('/login', [CustomerController::class, 'show_login'])->name('login')->middleware('guest');
    Route::post('/login', [CustomerController::class, 'login'])->name('login.attempt');
    Route::get('/register', [CustomerController::class, 'show_register'])->name('customer.register');
    Route::post('/register', [CustomerController::class, 'register'])->name('register.attempt');
    Route::get('/verify-otp', [CustomerController::class, 'show_otp'])->name('show.otppage');
    Route::get('/getproduct-details/{id?}', [FrontEndController::class, 'getProductDetails'])->name('getproduct.details');
    Route::post('/verification-otp', [CustomerController::class, 'verifyOtp'])->name('otp.verify');
    Route::post('/logout', [CustomerController::class, 'logout'])->name('logout');
});

Route::get('/home-feed', 'FrontEndController@homeFeed')->name('homefeed')->middleware('auth:customer', 'verified');
Route::middleware('guest')->group(function () {
    Route::get('/category-products/{name?}/', 'FrontEndController@categoryDetail')->name('category.detail');
    Route::get('/product-detail/{id?}/', 'FrontEndController@productDetail')->name('product.detail');
    Route::get('/product-cart/{qty}/{productid}', 'FrontEndController@productCart')->name('cart.index');
    Route::get('/product-subscribe/{id}', 'FrontEndController@productSubscribe')->name('subscribe.index');
    Route::post('/product-placed-order', 'FrontEndController@productPlacedOrder')->name('placed.order');
    Route::post('/coupon-radeem', 'FrontEndController@redeemCoupon')->name('coupon.radeem');
    Route::post('customer/order/subscription', 'FrontEndController@subscription');
    Route::get('customer/order/subscription-history', 'FrontEndController@subscriptionHistory')->name('customer.subscription.history');
    Route::Post('customer/order/subscription-detail', 'FrontEndController@subscriptionDetail')->name('customer.subscription.detail');
    Route::get('customer/order/jar-history/{id?}', 'FrontEndController@jarHistory')->name('customer.jar.history');
    Route::get('/customer-qr-show', 'Customer\CustomerController@showQr')->name('customer.qr');
    Route::get('customer/wallet-history', 'FrontEndController@walletHistory')->name('customer.wallet.history');
    Route::post('placed_order-schedule', 'FrontEndController@placedOrderSchedule')->name('');
    Route::get('/product-result', 'FrontEndController@search')->name('product.search');
    Route::get('/customer/feedback', 'CustomerController@feedback')->name('customer.feedback');
    Route::post('/customer/feedback/save', 'CustomerController@saveFeedback')->name('customer.feedback.save');
    Route::get('/customer/complain', 'CustomerController@complain')->name('customer.complain');
    Route::post('/customer/complain/save', 'CustomerController@saveComplain')->name('customer.complain.save');
});

// home feed products list



Route::get('/git-pull', 'Api\CommandController@gitpull');
Route::get('/artisan/{name}', 'Api\CommandController@artisanCommand');


Auth::routes();
Route::middleware('auth:web')->group(function () {
    Route::get('/home', 'DashboardController@index')->name('dashboard');
    Route::get('/profile', 'DashboardController@profile')->name('profile');
    Route::post('/profile-save', 'DashboardController@general')->name('profile.save');
    Route::post('/password-save', 'DashboardController@password')->name('password.save');

    // Coupon
    Route::prefix('/coupon')->group(function () {
        Route::get('/', 'CouponController@index')->name('coupon');
        Route::post('/store', 'CouponController@store');
        Route::post('/show', 'CouponController@show');
        Route::get('/{id}/edit', 'CouponController@edit');
        Route::post('/update', 'CouponController@update');
        Route::get('/delete/{id}', 'CouponController@delete');
    });

    // Vendor
    Route::prefix('/vendors')->name('vendor.')->group(function () {
        Route::get('/', 'VendorController@list')->name('list');
        Route::get('/add', 'VendorController@add')->name('add');
        Route::get('/edit/{id?}', 'VendorController@edit')->name('edit');
        Route::post('/save/{id?}', 'VendorController@save')->name('save');
        Route::get('/delete/{id}', 'VendorController@delete')->name('delete');
        Route::get('/approve/{id}', 'VendorController@isApprove')->name('is-approve');
        Route::get('/active/{id}', 'VendorController@isActive')->name('is-active');
        Route::get('/document/view/{id}', 'VendorController@documentView')->name('document.view');
        Route::get('/details/{id}', 'VendorController@detail')->name('detail');
    });
    //complains
    Route::prefix('/complains')->name('complain.')->group(function () {
        Route::get('/', 'ComplainController@list')->name('list');
        Route::get('/add', 'ComplainController@add')->name('add');
        Route::post('/save', 'ComplainController@save')->name('save');
        Route::get('/reply/{id}', 'ComplainController@reply')->name('reply');
        Route::post('/response/{id}', 'ComplainController@response')->name('response');
        Route::get('/delete/{id}', 'ComplainController@delete')->name('delete');
        Route::get('/approve/{id}', 'ComplainController@isApprove')->name('is-approve');
    });

    // QR Code
    Route::prefix('/QR')->group(function () {
        Route::get('/list/{id?}', 'QrCodeController@index');
        Route::get('/Reset/{id}', 'QrCodeController@Reset');
        Route::get('/create', 'QrCodeController@create')->name('QR.CREATE');
    });
    Route::prefix('/customer')->group(function () {
        Route::get('/', 'CustomerController@index')->name('customer.list');
        Route::get('/create', 'CustomerController@create')->name('customer.create');
        Route::post('/store', 'CustomerController@store')->name('customer.store');
        Route::get('/edit/{id}', 'CustomerController@edit')->name('customer.edit');
        Route::get('/view/{id}', 'CustomerController@view')->name('customer.view');
        Route::post('/update', 'CustomerController@update')->name('customer.update');
        Route::get('/delete/{id}', 'CustomerController@delete')->name('customer.delete');
        Route::post('/post-assign-group', 'CustomerController@postAssignGroup')->name('post-assign-group');
    });

    Route::prefix('new/customers')->name('newcustomer.')->group(function () {
        Route::get('/{id?}', 'AssignVendorController@list')->name('list');
        Route::get('/view/{id}', 'AssignVendorController@view')->name('view');
        Route::post('/assign-vendor{id}', 'AssignVendorController@assignVendor')->name('assign');
    });
    //invoice
    Route::prefix('/invoice')->name('invoice.')->group(function () {
        Route::get('/list', 'InvoiceController@index')->name('list');
        Route::get('/view', 'InvoiceController@view')->name('view');
    });
    //group
    Route::prefix('/group')->name('group.')->group(function () {
        Route::get('/list', 'GroupController@index')->name('list');
        Route::get('/create', 'GroupController@create')->name('create');
        Route::post('/store', 'GroupController@store')->name('store');
        Route::get('/member/{id}', 'GroupController@groupCustomer')->name('customer');
        Route::post('/change-member-position', 'GroupController@ChangeMemberPosition')->name('change.member.position');
    });
    //category
    Route::prefix('/category')->name('category.')->group(function () {
        Route::get('/list', 'CategoryController@index')->name('list');
        Route::get('/create', 'CategoryController@create')->name('create');
        Route::post('/store', 'CategoryController@store')->name('store');
    });
    //product
    Route::prefix('/product')->name('product.')->group(function () {
        Route::get('/list', 'ProductController@index')->name('list');
        Route::get('/create', 'ProductController@create')->name('create');
        Route::Post('/store', 'ProductController@store')->name('store');
    });
    //product
    Route::prefix('/deliveryboy')->name('deliveryboy.')->group(function () {
        Route::get('/list', 'DeliveryBoyController@index')->name('list');
        Route::get('/create', 'DeliveryBoyController@create')->name('create');
        Route::Post('/store', 'DeliveryBoyController@store')->name('store');
        Route::get('/assign-group/{id}', 'DeliveryBoyController@assignGroup')->name('assign-group');
        Route::post('/post-assign-group', 'DeliveryBoyController@postAssignGroup')->name('post-assign-group');
        Route::get('/delete/{id}', 'DeliveryBoyController@delete')->name('delete');
        Route::get('/edit/{id}', 'DeliveryBoyController@edit')->name('edit');
        Route::post('/update', 'DeliveryBoyController@update')->name('update');
    });
    //feedback
    Route::prefix('/feedback')->name('feedback.')->group(function () {
        Route::get('/list', 'FeedbackController@list')->name('list');
        Route::get('/view', 'FeedbackController@view')->name('view');
        Route::get('/add', 'FeedbackController@add')->name('add');

app/Feedback.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Feedback extends Model
{
    protected $guarded=[];
}

app/Http/Controllers/FeedbackController.php
<?php

namespace App\Http\Controllers;

use App\Feedback;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class FeedbackController extends Controller
{
    public function list()
    {
        $feedback = Feedback::all();
        return view('feedback.list', compact('feedback'));
    }
    public function add()
    {
        $user = Auth::user();
        return view('feedback.add',compact('user'));
    }
    public function save(Request $request)
    {

        $complain =   Feedback::create([
            "user_id"        => Auth::id(),
            "name"           => $request->name,
            "phone_number"   => $request->phone_number,
            "feedback"        =>  $request->feedback
        ]);

        return redirect()->route('feedback.list');
    }
    public function reply(Request $request, $id)
    {
        $feedback = Feedback::find($id);
        $replyto = User::where('id',$feedback->user_id)->get();
        return view('feedback.reply', compact('feedback','replyto'));
    }
    public function response(Request $request, $id)
    {
        $feedback = Feedback::find($id);
        $feedback->feedback_reply = $request->feedback_reply;
        $feedback->save();
        return redirect()->route('feedback.list');
    }



}

resources/views/feedback/add.blade.php
@extends('portal.layouts.app')
@section('content')

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Dashboard</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item active">Add Feedback</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- Main content -->
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('feedback.save') }}" method="POST" class="card-box" autocomplete="off">
                        @csrf
                        <div class="form-group">
                            <label for="exampleInputName">Name</label>
                            <input type="name" name="name" class="form-control" id="exampleInputName"
                                placeholder="Enter Name" required value="{{ Auth::user()->name }}">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputName">Mobile</label>
                            <input type="name" name="phone_number" class="form-control" id="exampleInputNum"
                                placeholder="Enter Mobile number" required value="{{ Auth::user()->phone_number ?? '' }}">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputBName">Your Complain</label>
                            <textarea id="editor" class="editor" name="feedback"></textarea>
                        </div>
                </div>
                <div class="form-group pr-3">
                    <a href="{{ route('complain.list') }}"
                        class="btn btn-danger btn-sm text-light px-4 mt-3 float-right mb-0 ml-2">Cancel</a>
                    <button type="submit" class="btn btn-primary btn-sm text-light px-4 mt-3 float-right mb-0">Register
                        Feedback</button>
                </div>
                </form>
            </div>
        </div>
    </div>
    </div>
    <!-- /.content -->

    <!-- /.content-wrapper -->

@endsection

resources/views/feedback/list.blade.php
@extends('portal.layouts.app')

@section('content')

 <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{url('home')}}">Home</a></li>
              <li class="breadcrumb-item active">Feedback List</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- Main content -->

    <!-- /.content -->
    <div class="row">
        <div class=" m-2 col-lg-3">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-4 align-self-center">
                            <div class="icon-info">
                                <i class="fa fa-user fa-2x" aria-hidden="true" ></i>
                            </div>
                        </div>
                        <div class="col-8 align-self-center text-right">
                            <div class="ml-2">
                                <p class="mb-1 text-muted">Total Feedback </p>
                                <input class=" h3 mt-0 mb-1 font-weight-semibold text-center" name="" id=""
                                    value="{{ totalFeedback() }}" readonly
                                    style="background: transparent; border: none;margin-left: -30px">
                            </div>
                        </div>
                    </div>
                </div>
                <!--end card-body-->
            </div>
            <!--end card-->
        </div>
    </div>

    <div class="row">
        @if(auth()->user()->id != 1)
        <div class="col-md-12 text-right pr-3">
            <a href="{{ route('feedback.add') }}" class="btn btn-primary px-4 mt-0 mb-3"><i
                    class="mdi mdi-plus-circle-outline mr-2"></i>Add New</a>
          </div>
        @endif
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="datatable" class="table">
                            <thead class="thead-light">
                                <tr>
                                    <th>Name</th>
                                    <th>Phone Number</th>
                                    <th>Feedback</th>
                                    <th>Reply</th>
                                    @if(auth()->user()->id==1)
                                    <th class="text-right">Action</th>
                                    @endif
                                </tr>
                                <!--end tr-->
                            </thead>
                            <tbody>
                                @foreach ($feedback as $index => $data)
                                @if(auth()->user()->id==1 || $data->user_id==auth()->user()->id)
                                   <tr>
                                       <td>{{ $data->name }}</td>
                                       <td>{{ $data->phone_number }}</td>
                                       <td>{!! $data->feedback !!}</td>
                                       <td>{!! $data->feedback_reply !!}</td>
                                       <td>
                                           @if(Auth::user()->role_id==1)
                                            <a href="{{ route('feedback.reply', $data->id) }}" class="btn btn-sm btn-primary">Pay Thanks</a>
                                           @endif

                                        </td>
                                   </tr>
                                   @endif
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
  <!-- /.content-wrapper -->

@endsection

resources/views/feedback/reply.blade.php
@extends('portal.layouts.app')

@section('content')

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Dashboard</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
                        <li class="breadcrumb-item active">Pay Thanks</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- Main content -->
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('feedback.response', $feedback->id) }}" method="POST" class="card-box" autocomplete="off">
                        @csrf
                        <div class="form-group">
                            <label for="exampleInputBName">Your Reply</label>
                            <textarea id="editor" class="editor" name="feedback_reply"></textarea>
                        </div>
                </div>
                <div class="form-group pr-3">
                    <a href="{{ route('feedback.list') }}"
                        class="btn btn-danger btn-sm text-light px-4 mt-3 float-right mb-0 ml-2">Cancel</a>
                    <button type="submit" class="btn btn-primary btn-sm text-light px-4 mt-3 float-right mb-0">
                        Reply Now</button>
                </div>
                </form>
            </div>
        </div>
    </div>
    </div>
    <!-- /.content -->

    <!-- /.content-wrapper -->

@endsection